[colors.bright]
black = "#545454"
blue = "#569cd6"
cyan = "#56b6c2"
green = "#a6e3a1"
magenta = "#c678dd"
red = "#f44747"
white = "#d4d4d4"
yellow = "#dcdcaa"

[colors.cursor]
cursor = "#d4d4d4"
text = "#d4d4d4"

[colors.normal]
black = "#1e1e1e"
blue = "#569cd6"
cyan = "#56b6c2"
green = "#a6e3a1"
magenta = "#c678dd"
red = "#f44747"
white = "#d4d4d4"
yellow = "#dcdcaa"

[colors.primary]
background = "#000000"
foreground = "#000000"
