#! /usr/bin/env bash

function backup(){
  backup_name="backup-$(date -u +%Y-%m-%dT%H-%M-%S).tar.gz"
  # backup_name="backup.tar.gz"
  if [[ $# -eq 0 ]]
  then
    echo "Usage : backup file/folder file/folder .."
  else
    tar -czvf $backup_name $@
  fi
}

backup $@
