#! /usr/bin/env bash

LOFI_LINK="https://www.youtube.com/watch?v=jfKfPfyJRdk"
SYNTHWAVE_LINK="https://www.youtube.com/watch?v=4xDzrJKXOOY"
UPBEATS_LINK="https://www.youtube.com/watch?v=wELOA2U7FPQ"
VOLUME=30
# mpv $STREAM_LINK --no-video 2>/dev/null

function lofi(){
    notify-send "Lofi time 🎶"
    mpv $LOFI_LINK --no-video --msg-level=all=no,statusline=status --volume=$VOLUME
}

function synthwave(){
    notify-send "Synthwave time 🎧"
    mpv $SYNTHWAVE_LINK --no-video --msg-level=all=no,statusline=status --volume=$VOLUME
}

function upbeats(){
    notify-send "Upbeats time ⚡"
    mpv $UPBEATS_LINK --no-video --msg-level=all=no,statusline=status --volume=$VOLUME
}

function main(){
    if [[ $1 == "synthwave" ]]; then
        synthwave
    elif [[ $1 == "lofi" ]]; then
        lofi
    elif [[ $1 == "upbeats" ]]; then
        upbeats
    else
        echo "Usage: beats [synthwave|lofi|upbeats]"
    fi
}

main $1
