#! /usr/bin/env bash

function qrc(){
  if [[ $# -eq 1 ]]
  then
    link=$1
    echo $link
    qrencode -t ansiutf8 $link
  else
    link=$(wl-paste)
    echo $link
    qrencode -t ansiutf8 $link
  fi
}

qrc $@
